FROM dunglas/frankenphp:1-php8.3-bookworm

RUN install-php-extensions \
    mysqli \
    pdo_mysql \
    curl \
    gd

WORKDIR /app/public

COPY . /app/public

COPY Caddyfile /etc/caddy/Caddyfile

CMD ["frankenphp", "run", "--config", "/etc/caddy/Caddyfile"]